module.exports.Chemical = require('./lib/Chemical')
module.exports.DNA = require('./lib/DNA')
module.exports.Nucleus = require('./lib/Nucleus')
module.exports.Organel = require('./lib/Organel')
module.exports.Plasma = require('./lib/Plasma')
